validate bbox in json
PEM-Humboldt/biotablero-search-backend pull request #22
Opened 2024-07-15 18:41 UTC by denarch22

## 🛠️ Changes
Make adjustments to the code to be able to perform validations in bbox and add its structure

## 📝 Associated issues
[Validación para el bbox](https://app.zenhub.com/workspaces/all-5f7f96a92b54ca00239a9348/issues/gh/pem-humboldt/biotablero-search-backend/18)

2024-07-15 22:53 UTC, erikasv requested changes
Before I can review the changes related with the bbox validation please revert the changes made to the endpooint `GET /{metric_id}/areas` (previous function `get_areas_by_defined_area`), this function is not implemented yet.

The validation requested in the task affects only the POST endpoints which are the ones that receive polygons, the GET endpoints must remain the same. Also leave the functions documentation in english

2024-07-15 22:53 UTC, erikasv commented on app/routes/metrics.py
> +from typing import Annotated, Literal, List, Union
Change this import (see "Importación" in "Acuerdos de Estilo" for the [agreements in python projects](https://docs.google.com/document/d/1PQOE35s5OkW3N5B9V5ql27__btKW6qyvl6vRvK7yG_w/edit)

2024-07-15 22:53 UTC, erikasv commented on app/routes/metrics.py
> +from fastapi import Depends, HTTPException, Path
fastapi is already imported

2024-07-15 23:36 UTC, denarch22 commented
@erikasv I have already finished the recommended corrections, I remain attentive to any recommendation

2024-07-16 14:32 UTC, cazapatamar commented
Please link the zenhub issue in the option "Connect existing issues to this pull request" @denarch22

2024-07-16 15:53 UTC, erikasv requested changes, later dismissed

2024-07-16 15:53 UTC, erikasv commented on app/routes/metrics.py
> +    metric_id: str,
According to the change in `get_areas_by_defined_area` this param should change its annotation and the new `metric_id_param` in this function should be deleted

2024-07-16 15:53 UTC, erikasv commented on app/routes/metrics.py
> +        # Validación adicional si se desea
remove this comment

2024-07-16 15:53 UTC, erikasv commented on app/routes/metrics.py
> +        # Lógica para obtener áreas basadas en el polígono
remove this comment

2024-07-16 15:53 UTC, erikasv commented on app/routes/metrics.py
> +    PolygonRequest,
this import is not being used

2024-07-16 15:53 UTC, erikasv commented on app/routes/metrics.py
> +        return [
when you rebased the branch you lost the implementation of this endpoint, see [develop](https://github.com/PEM-Humboldt/biotablero-search-backend/blob/develop/app/routes/metrics.py#L91)

2024-07-16 15:53 UTC, erikasv commented on app/routes/metrics.py
> +    "/{metric_id}/areas/defined", response_model=typing.List[AreasResponse]
we didn't have this endpoint and I see is the previous implementation of `get_areas_by_polygon` we don't have such thing as "predefined polygon". Please delete this function and adjust `get_areas_by_polygon`

2024-07-16 15:53 UTC, erikasv commented on app/routes/metrics.py
> +    polygon: FeatureRequest,
this param should be the same type as the one for `get_areas_by_polygon`

2024-07-16 15:53 UTC, erikasv commented on app/routes/schemas/polygon.py
> +from app.services.utils import context_vars
this import is not being used

2024-07-16 15:53 UTC, erikasv commented on app/routes/schemas/polygon.py
apart from the names I see a good implementation, the issue is that you're reimplementing the models that geojson-pydantic has (and now is not being used), but in this way some validation are missing.

I suggest you to return using the geojson_pydantic model and see if you can make the bbox required instead of optional. See the [base model implementation](https://github.com/developmentseed/geojson-pydantic/blob/main/geojson_pydantic/base.py#L26)

We could handle the bbox in the feature instead of the geometry (maybe that is where it should be and we've been using it wrong) and you could extend the [Feature model](https://github.com/developmentseed/geojson-pydantic/blob/main/geojson_pydantic/features.py#L14) and specify the Polygon geometry as explained in the [advanced-usage](https://developmentseed.org/geojson-pydantic/intro/#advanced-usage)

2024-07-19 20:37 UTC, denarch22 commented
Perform the validation and investigate that using the field_validator annotation and the mode before it performs the validation of the bbox before any validation immersed in the geojson, it is to be clarified that it does not affect the validation of other fields or properties of the JSON, I remain attentive for the respective review

2024-07-19 20:41 UTC, erikasv commented on .idea/workspace.xml
please remove this file and add it to the .gitignore (we do not enforce the use of any ide)

2024-07-19 20:43 UTC, erikasv reviewed
lgtm, just the idea config thing.

I can't test it right now, please @ManuelStardust test the functionality.

2024-07-19 20:45 UTC, denarch22 commented on .idea/workspace.xml
ok

2024-07-19 20:46 UTC, denarch22 commented on .idea/workspace.xml
Deleted

2024-07-19 22:28 UTC, ManuelStardust approved these changes
I tested and it works fine.

2024-07-19 22:48 UTC, merged