Implementing migrations with Aerich
PEM-Humboldt/biotablero-search-backend pull request #57
Opened 2024-12-17 00:31 UTC by denarch22

## 🛠️ Changes
The implementation was carried out to be able to make structural changes using the migrations performed by the Tortoise tool with Aerich

## 📝 Associated issues
#56

2024-12-17 20:53 UTC, erikasv requested changes
Tengo algunas dudas y comentarios:
- la carpeta migrations no está versionada, por qué?
- No se debería ejecutar init ni init-db al iniciar la aplicación, estos comandos están pensados para correrlos una sola vez y así se deben documentar en el readme
- Tal como está en el readme (y en la documentación de aerich) migrate se usa es para crear una nueva migración, así que tampoco entiendo para qué se corren al inicio de la aplicación
- En general no me parece adecuado que se corran las migraciones al iniciar el servidor

Aunque no resultó tan mal como lo pensé inicialmente, no le veo ningún beneficio el tener el endpoint para las migraciones, sobretodo porque los comandos no requieren que el servidor esté corriendo y el tener que crear y correr nuevas migraciones será algo más bien esporádico.

__Importante__: Los cambios que se hagan sobre los modelos guardarlos como una segunda migración (para poder probar la actualización también)

2024-12-17 20:53 UTC, erikasv commented on docker-compose.yml
> +      - "5432:5432"
Es mejor cambiar el puerto en el host, muchos desarrolladores tienen instalado postgres en sus máquinas y esto va a dar problemas

2024-12-17 20:53 UTC, erikasv commented on docker-compose.yml
> +    image: postgres:latest
mejor no usar "latest", para controlar los cambios que puedan haber en versiones, poner la versión "latest" en este momento

2024-12-17 20:53 UTC, erikasv commented on docker-compose.yml
> +  app-network:
mejor usar otro nombre, tal vez `bt-search-network` ? (app-network es muy genérico y da para confusiones)

2024-12-17 20:53 UTC, erikasv commented on docker-compose.yml
> +    container_name: db
mejor usar otro nombre, tal vez bt-search-db ? (db es muy genérico y da para confusiones)

2024-12-17 20:53 UTC, erikasv commented on README.md
>     USER_HASHED_PASSWORD="" # authentication password
Finalmente las variables relacionadas con crear la capa de autenticación no se van a usar en este repositorio, favor quitarlas de aquí y del env.sample

2024-12-17 20:53 UTC, erikasv commented on README.md
> +1. **Initialize `aerich`** :
Estos comandos están más a manera informativa que para seguirlos en este orden. Mejor quitar la numeración y dejar viñetas

2024-12-17 20:53 UTC, erikasv commented on README.md
> +* **Endpoint**:
Quitar esta viñeta

2024-12-17 20:53 UTC, erikasv commented on README.md
> +
eliminar una línea en blanco

2024-12-17 20:53 UTC, erikasv commented on README.md
> +
eliminar una línea en blanco

2024-12-17 20:53 UTC, erikasv commented on README.md
> +## Database Migrations
Creo que esto va mejor al final, después de la documentación

2024-12-17 20:53 UTC, erikasv commented on app/models/models.py
> +class SpatialRefSys(Model):
Esta tabla se crea automáticamente por la extensión de postgis y no estoy convencida de que debamos crearle un modelo en la aplicación

2024-12-17 20:53 UTC, erikasv commented on README.md
> +   aerich init -t app.config.TORTOISE_ORM
la ruta a la configuración está mal

2024-12-17 20:53 UTC, erikasv commented on app/services/migrations.py
los logs de este archivo deben ir en inglés

2024-12-17 20:53 UTC, erikasv commented on app/main.py
> +            extra={"request_id": request_id_context.get()},
En toda esta función no existe request_id

2024-12-17 20:53 UTC, erikasv commented on app/models/models.py
> +    )  # Ajusta el tipo si es diferente
eliminar comentario.

2024-12-17 20:53 UTC, erikasv commented on app/models/models.py
> +    polygon_id = fields.IntField(pk=True)
mejor renombrar a id

2024-12-17 20:53 UTC, erikasv commented on app/models/models.py
> +    metric_polygon_id = fields.IntField(pk=True)
mejor renombrar a id

2024-12-17 20:53 UTC, erikasv commented on app/models/models.py
> +    item_id = fields.IntField(pk=True)
mejor renombrar a id

2024-12-23 19:55 UTC, erikasv requested changes
Falta incluir las migraciones en el PR, en la revisión anterior dejé esta nota:

> __Importante__: Los cambios que se hagan sobre los modelos guardarlos como una segunda migración (para poder probar la actualización también)

Así que hacen falta dos migraciones. Te toca crear la primera migración con la versión previa de los modelos y la segunda donde se haga el cambio de los nombres de los campos

2024-12-23 19:55 UTC, erikasv commented on migrations/.gitkeep
Este archivo es innecesario

2024-12-23 19:55 UTC, erikasv commented on app/utils/config.py
> +    db_port: int = 5432
El valor por defecto debe coincidir con el asignado al host en el docker-compose

2024-12-23 19:55 UTC, erikasv commented on app/utils/config.py
> +    db_host: str = ""
el valor por defecto debe ser localhost

2024-12-23 19:55 UTC, erikasv commented on README.md
> +   DB_PORT=5432 # Database port (default for PostgreSQL)
el ejemplo debe coincidir con el valor asignado en el docker-compose

2024-12-23 21:00 UTC, denarch22 commented
> Falta incluir las migraciones en el PR, en la revisión anterior dejé esta nota:
> 
> > **Importante**: Los cambios que se hagan sobre los modelos guardarlos como una segunda migración (para poder probar la actualización también)
> 
> Así que hacen falta dos migraciones. Te toca crear la primera migración con la versión previa de los modelos y la segunda donde se haga el cambio de los nombres de los campos

ok, igualmente aclaro que los nombre se cambian dentro del archivo models para que genere el archivo update

2024-12-24 12:34 UTC, erikasv requested changes
Falta instalar la extensión de postgis para poder almacenar rasters. Eso implica cambiar la imagen del docker que se está usando.

2024-12-24 12:34 UTC, erikasv commented on requirements.txt
> +aerich>=0.8.0
poner un límite superior como con las demás dependencias

2024-12-24 12:34 UTC, erikasv commented on README.md
>  1. Run the the development server
Antes de este paso agregar uno que sea `Run database migrations` donde se indique correr el comando `aerich upgrade`, esto es independiente de la documentación total sobre las migraciones que está más abajo.

2024-12-24 12:34 UTC, erikasv commented on app/models/models.py
> +    description = fields.TextField(null=True)
para qué es este campo? no está en el diseño inicial

2024-12-24 12:34 UTC, erikasv commented on migrations/models/1_20241223155332_update.py
No le veo sentido a esta migración, en la nota de la primera revisión decía que los cambios hechos a los modelos se debían poner como otra migración, los cambios de los modelos era el cambio de las llaves primaras por `id` en lugar de los nombres que tenían antes.

2025-01-08 16:03 UTC, erikasv requested changes
Solo el tema de las versiones, de resto ya todo está ok

2025-01-08 16:03 UTC, erikasv commented on docker-compose.yml
> +    image: postgis/postgis:15-3.3
por qué postgres 15 y postgis 3.3?

Deberíamos usar postgres 17 o al menos 16 (ver la [política de versiones](https://www.postgresql.org/support/versioning/))

Y de acuerdo a la fecha del release de postgis, deberíamos usar al menos la 3.4

2025-01-08 17:35 UTC, denarch22 commented on docker-compose.yml
> +    image: postgis/postgis:15-3.3
Lo realice porque en ese momento encontre esas versiones compatibles, pero para este año ya actualizaron a la 17-3.5

2025-01-08 17:38 UTC, erikasv approved these changes

2025-01-09 02:46 UTC, merged